### PR TITLE
[ W.I.P ] Adding New Rating Things From Friday Night Dustin'

### PR DESCRIPTION
**Pull request by moxie-coder**

### CODE REVIEW

**Comment by LEVIXDDLMAO** [comment]
Hoovy said its not done it,

**Comment by LEVIXDDLMAO** [comment]
its broken rn

**Comment by moxie-coder** [comment]
> its broken rn

ye

**Comment by LEVIXDDLMAO** [comment]
hoovy's working on a fix
________________________________

**Review by LEVIXDDLMAO — COMMENTED** [review]
I Asked Him to do this, but I dont think its posssible, as of now without Friday Night Dustin' Source, Unless Hoovy allows you to help him with this project

**Comment by moxie-coder** [comment]
> I Asked Him to do this, but I dont think its posssible, as of now without Friday Night Dustin' Source, Unless Hoovy allows you to help him with this project

sure I'll allow sanco to help

**Comment by LEVIXDDLMAO** [comment]
> > I Asked Him to do this, but I dont think its posssible, as of now without Friday Night Dustin' Source, Unless Hoovy allows you to help him with this project
> 
> sure I'll allow sanco to help

alright any updates?

**Comment by moxie-coder** [comment]
> > > I Asked Him to do this, but I dont think its posssible, as of now without Friday Night Dustin' Source, Unless Hoovy allows you to help him with this project
> > 
> > 
> > sure I'll allow sanco to help
> 
> alright any updates?

not yet

**Comment by LEVIXDDLMAO** [comment]
alright

**Comment by moxie-coder** [comment]
alright I sent him an invite

**Comment by LEVIXDDLMAO** [comment]
cool

**Comment by SanicBTW** [comment]
Aight what up bois

**Comment by moxie-coder** [comment]
> Aight what up bois

I invited you to my fork so you can help

**Pull request closed without merging**
